# Tejas Database Monitoring Application Configuration Template
# Copy this file to config.yaml and fill in your actual values

# Database Configuration
database:
  host: localhost
  port: 5433
  name: testdb
  user: postgres
  password: ${DB_PASSWORD}
  
# Application Configuration
app:
  debug: true
  host: "0.0.0.0"
  port: 8000
  
# Agent Configuration
agent:
  check_interval: 30  # seconds between ticket checks
  enabled: true
  
# Logging Configuration
logging:
  level: INFO
  
# Docker Configuration (for reference)
docker:
  postgres:
    image: postgres:15
    internal_port: 5432
    external_port: 5433

# Model Configuration
model:
  name: "gpt-4o"
  api_key: ${ANTHROPIC_API_KEY}
