query_status_check:
  description: "Check the status of database queries, particularly looking for long-running ones"
  expected_output: "Status report of active database queries"
  agent: database_administrator

connection_info_check:
  description: "Get current database connection information and statistics"
  expected_output: "Database connection statistics and information"
  agent: database_administrator

query_management:
  description: "If there are problematic long-running queries, consider terminating them. Use your judgment."
  expected_output: "Query management action taken or recommendation"
  agent: database_administrator
